using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HermesProxy.World.Enums.V3_4_3_54261
{
    public enum ResponseCodes : byte
    {
        Success = 0,
        Failure = 1,
        Cancelled = 2,
        Disconnected = 3,
        FailedToConnect = 4,
        Connected = 5,
        VersionMismatch = 6,

        CStatusConnecting = 7,
        CStatusNegotiatingSecurity = 8,
        CStatusNegotiationComplete = 9,
        CStatusNegotiationFailed = 10,
        CStatusAuthenticating = 11,

        RealmListInProgress = 12,
        RealmListSuccess = 13,
        RealmListFailed = 14,
        RealmListInvalid = 15,
        RealmListRealmNotFound = 16,

        AccountCreateInProgress = 17,
        AccountCreateSuccess = 18,
        AccountCreateFailed = 19,

        CharListRetrieving = 20,
        CharListRetrieved = 21,
        CharListFailed = 22,

        CharCreateInProgress = 23,
        CharCreateSuccess = 24,
        CharCreateError = 25,
        CharCreateFailed = 26,
        CharCreateNameInUse = 27,
        CharCreateDisabled = 28,
        CharCreatePvpTeamsViolation = 29,
        CharCreateServerLimit = 30,
        CharCreateAccountLimit = 31,
        CharCreateServerQueue = 32,
        CharCreateOnlyExisting = 33,
        CharCreateExpansion = 34,
        CharCreateExpansionClass = 35,
        CharCreateCharacterInGuild = 36,
        CharCreateRestrictedRaceclass = 37,
        CharCreateCharacterChooseRace = 38,
        CharCreateCharacterArenaLeader = 39,
        CharCreateCharacterArenaTeam = 40,
        CharCreateCharacterDeleteMail = 41,
        CharCreateCharacterSwapFaction = 42,
        CharCreateCharacterRaceOnly = 43,
        CharCreateCharacterGoldLimit = 44,
        CharCreateForceLogin = 45,
        CharCreateTrial = 46,
        CharCreateTimeout = 47,
        CharCreateThrottle = 48,
        CharCreateAlliedRaceAchievement = 49,
        CharCreateCharacterInCommunity = 50,
        CharCreateNewPlayer = 51,
        CharCreateNameReservationFull = 52,
        CharCreateDracthyrDuplicate = 53,
        CharCreateDracthyrLevelRequirement = 54,
        CharCreateDeathknightDuplicate = 55,
        CharCreateDeathknightLevelRequirement = 56,
        CharCreateClassTrialNewcomer = 57,
        CharCreateClassTrialThrottleHour = 58,
        CharCreateClassTrialThrottleDay = 59,
        CharCreateClassTrialThrottleWeek = 60,
        CharCreateClassTrialThrottleAccount = 61,

        CharDeleteInProgress = 62,
        CharDeleteSuccess = 63,
        CharDeleteFailed = 64,
        CharDeleteFailedLockedForTransfer = 65,
        CharDeleteFailedGuildLeader = 66,
        CharDeleteFailedArenaCaptain = 67,
        CharDeleteFailedHasHeirloomOrMail = 68,
        CharDeleteFailedUpgradeInProgress = 69,
        CharDeleteFailedHasWowToken = 70,
        CharDeleteFailedVasTransactionInProgress = 71,
        CharDeleteFailedCommunityOwner = 72,

        CharLoginInProgress = 73,
        CharLoginSuccess = 74,
        CharLoginNoWorld = 75,
        CharLoginDuplicateCharacter = 76,
        CharLoginNoInstances = 77,
        CharLoginFailed = 78,
        CharLoginDisabled = 79,
        CharLoginNoCharacter = 80,
        CharLoginLockedForTransfer = 81,
        CharLoginLockedByBilling = 82,
        CharLoginLockedByMobileAh = 83,
        CharLoginTemporaryGmLock = 84,
        CharLoginLockedByCharacterUpgrade = 85,
        CharLoginLockedByRevokedCharacterUpgrade = 86,
        CharLoginLockedByRevokedVasTransaction = 87,
        CharLoginLockedByRestriction = 88,
        CharLoginLockedForRealmPlaytype = 89,

        CharNameSuccess = 90,
        CharNameFailure = 91,
        CharNameNoName = 92,
        CharNameTooShort = 93,
        CharNameTooLong = 94,
        CharNameInvalidCharacter = 95,
        CharNameMixedLanguages = 96,
        CharNameProfane = 97,
        CharNameReserved = 98,
        CharNameInvalidApostrophe = 99,
        CharNameMultipleApostrophes = 100,
        CharNameThreeConsecutive = 101,
        CharNameInvalidSpace = 102,
        CharNameConsecutiveSpaces = 103,
        CharNameRussianConsecutiveSilentCharacters = 104,
        CharNameRussianSilentCharacterAtBeginningOrEnd = 105,
        CharNameDeclensionDoesntMatchBaseName = 106,
        CharNameSpacesDisallowed = 107,

    }
}
